version: "3.8"

services:
  php:
    build: .
    container_name: symfony-app
    volumes:
      - ./app:/var/www/app
    ports:
      - "8082:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: